import { React, useState ,useEffect} from 'react'
import NavBar from './components/NavBar'
import Home from './components/Homepage'
import Events from './components/Events'
import Marketplace from './components/Marketplace'
import { Route, Routes } from 'react-router-dom'
import Footer from './components/Footer'
import Card from './components/Card'
import './styles.css'
import SiteMap from './components/map'
import LoginPage from './components/LoginpageNew'
import SignUpPage from './components/SignupPage'
import AddNFTPage from './components/AddNFTpage'
import ProfilePage from './components/ProfilePage'
import Sidebar from './components/Sidebar'
import EventForm from './components/EventForm'
import AddNFTForm from './components/AddNFTform'
import MovieDetails from './components/MovieDetails'
import NFTBillingPage from './components/NFTBilling'
import Collectibles from './components/Collectibles'
import axios from 'axios'
 // import minter from './components/minter'
import Upload from './components/FileUpload'
import Map from './components/map'
const App = () => {
  const featuredSlides = [
    'https://autowithsid.in/wp-content/uploads/2023/06/Animal-Upcoming-Ranbir-Kapoor-Movie-2023.jpg',
    'https://bingeddata.s3.amazonaws.com/uploads/2022/05/Salaar-Poster-Teases-Prabhas-Kicking-Some-High-Octane-Action.jpg',
    'https://i.ytimg.com/vi/Kwmid4Ud1ao/maxresdefault.jpg'
  ];

  const upcomingSlides = [
    'https://images.travelandleisureasia.com/wp-content/uploads/sites/2/2022/12/30232004/arijit-singh.jpeg',
    'https://graphicsfamily.com/wp-content/uploads/edd/2021/07/Music-Concert-Event-Ticket-Design-1536x864.jpg',
    'https://s1.ticketm.net/dam/a/7d5/97b67038-f926-4676-be88-ebf94cb5c7d5_1802151_TABLET_LANDSCAPE_LARGE_16_9.jpg'
  ];
  const handleSubmit = (data) => {
    // Your handleSubmit logic here
    console.log('Submitted data:', data);
  };

  const [userData, setUserData] = useState({ email: '', username: '' });


  useEffect(() => {
    axios.get('http://localhost:5000/Profile', { withCredentials: true })
        .then(response => {
            const { msg, email, username } = response.data;
            // if (msg === "Success") {
                setUserData({ email, username });
            // } else {
                // navigate('/LoginpageNew');
            // }
        })
        .catch(error => {
            console.log(error);
        });
}, []);

  return (
    <>
      <NavBar />
      <Routes>
        <Route exact path="/" element={<Home />} />
        <Route path="/Events" element={<Events featuredSlides={featuredSlides} upcomingSlides={upcomingSlides} />} />
        <Route path="/MarketPlace" element={<Marketplace />} />
        <Route path="/LoginpageNew" element={<LoginPage />} />
        <Route path="/SignUpPage" element={<SignUpPage />} />
        <Route path="/Moviedetails" element={<MovieDetails posterUrl='https://i.seadn.io/s/raw/files/22085c96c432ffe169c3c1dec3c5097d.jpg?auto=format&dpr=1&w=512'
          title='Negative 1289 '
          description='"Traits randomly generated by code, and then assembled and photographed by hand.' />} />
        <Route path='/Profile' element={<ProfilePage username={userData.username} email={userData.email}/>} />
          // name="Niranjan More"
          // email="niranjanmore123@gmail.com"
          // username="NiranjanMore10"
        <Route path='/AddNFTform' element={<AddNFTForm onSubmit={handleSubmit} />} />
        <Route path='/EventForm' element={<EventForm />} />
        <Route path='/Collectibles' element={<Collectibles />} />
        {/* <Route path='/Minter' element={minter } />  */}
        <Route path='/Upload' element={<Upload onSubmit={handleSubmit}/>} /> 
        {/* onSubmit={handleSubmit} */}

      </Routes>
      <Footer />
      {/* <MovieDetails
        posterUrl='https://assets.raribleuserdata.com/prod/v1/image/t_avatar_big/aHR0cHM6Ly9pcGZzLnJhcmlibGV1c2VyZGF0YS5jb20vaXBmcy9iYWZ5YmVpZWw3NnQzZ2lnZ3ljbmR1ZXNmajc2dnpkdXNheWNkZmNrcXh2bXhzczJkNG9mYjdyNDJ6ZS9IRUFERkFDRTAxMDc3XzAwNjcucG5n'
        title='Rejoice '
        description='"Rejoice" is a vibrant and uplifting piece of art that captures the essence of joy and celebration like flowers in full bloom, the orb of light is a third eye as an homage to the other side.'
      /> */}
    </>

    /* <div className=' flex'>
      <Sidebar />
      <Routes>
        
      </Routes>
    </div> */



  )
}
export default App;
// App.js



// import { React, useState } from 'react'
// import NavBar from './components/NavBar'
// import Home from './components/Homepage'
// import Events from './components/Events'
// import Marketplace from './components/Marketplace'
// import { Route, Routes } from 'react-router-dom'
// import Footer from './components/Footer'
// import Card from './components/Card'
// import './styles.css'
// import SiteMap from './components/map'
// import LoginPage from './components/LoginpageNew'
// import SignUpPage from './components/SignupPage'
// import AddNFTPage from './components/AddNFTpage'
// import ProfilePage from './components/ProfilePage'
// import Sidebar from './components/Sidebar'
// import EventForm from './components/EventForm'
// import AddNFTForm from './components/AddNFTform'
// import MovieDetails from './components/MovieDetails'
// import NFTBillingPage from './components/NFTBilling'
// import Collectibles from './components/Collectibles'
// // import minter from './components/minter'
// import Upload from './components/FileUpload'
// import Map from './components/map'

// const App = () => {
//   const [userData, setUserData] = useState({
//     name: "Niranjan More",
//     email: "niranjanmore123@gmail.com",
//     username: "NiranjanMore10"
//   });

//   const featuredSlides = [
//     'https://autowithsid.in/wp-content/uploads/2023/06/Animal-Upcoming-Ranbir-Kapoor-Movie-2023.jpg',
//     'https://bingeddata.s3.amazonaws.com/uploads/2022/05/Salaar-Poster-Teases-Prabhas-Kicking-Some-High-Octane-Action.jpg',
//     'https://i.ytimg.com/vi/Kwmid4Ud1ao/maxresdefault.jpg'
//   ];

//   const upcomingSlides = [
//     'https://images.travelandleisureasia.com/wp-content/uploads/sites/2/2022/12/30232004/arijit-singh.jpeg',
//     'https://graphicsfamily.com/wp-content/uploads/edd/2021/07/Music-Concert-Event-Ticket-Design-1536x864.jpg',
//     'https://s1.ticketm.net/dam/a/7d5/97b67038-f926-4676-be88-ebf94cb5c7d5_1802151_TABLET_LANDSCAPE_LARGE_16_9.jpg'
//   ];

//   const handleSubmit = (data) => {
//     // Your handleSubmit logic here
//     console.log('Submitted data:', data);
//   };

//   return (
//     <>
//       <NavBar />
//       <Routes>
//         <Route exact path="/" element={<Home />} />
//         <Route path="/Events" element={<Events featuredSlides={featuredSlides} upcomingSlides={upcomingSlides} />} />
//         <Route path="/MarketPlace" element={<Marketplace />} />
//         <Route path="/LoginpageNew" element={<LoginPage />} />
//         <Route path="/SignUpPage" element={<SignUpPage />} />
//         <Route path="/Moviedetails" element={<MovieDetails posterUrl='https://i.seadn.io/s/raw/files/22085c96c432ffe169c3c1dec3c5097d.jpg?auto=format&dpr=1&w=512'
//           title='Negative 1289 '
//           description='"Traits randomly generated by code, and then assembled and photographed by hand.' />} />
//         <Route path='/Profile' element={<ProfilePage name={userData.name} email={userData.email} username={userData.username} />} />
//         <Route path='/AddNFTform' element={<AddNFTForm onSubmit={handleSubmit} />} />
//         <Route path='/EventForm' element={<EventForm />} />
//         <Route path='/Collectibles' element={<Collectibles />} />
//         {/* <Route path='/Minter' element={minter } />  */}
//         <Route path='/Upload' element={<Upload onSubmit={handleSubmit} />} />
//         {/* onSubmit={handleSubmit} */}
//       </Routes>
//       <Footer />
//     </>
//   );
// }

// export default App;

